---
abstract: 'Simple detection of binary versus text in strings'
author:
  - 'Stuart Watt <stuart@morungos.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Binary
requires:
  perl: '5.008000'
version: '0.01'
